- name: ansible command shell example
  hosts: local
  connection: local
  tasks:
    - name: Run a command on the local machine
      ansible.builtin.command: echo "Hello, Ansible!"
      registers: command_output

    - name: Display the command output
      ansible.builtin.debug:
        msg: "{{ command_output }}"  

    - name: Run a command on the local machine
      ansible.builtin.command: echo "Hello, Ansible!" >> output.txt

    - name: Run a command on the local machine
      ansible.builtin.command: ps -ef | grep ansible