- name: loops example to intall packages
  hosts: local
  connection: local
  tasks:
    - name: Loop through a list of packages and install them
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - mariadb-mysql-server
        - python3-pip
        - htop