- name: demo on filters
  hosts: local
  connection: local
  become: true
  vars:
    TOPICS: linux, ansible, automation, devops
    TagsMaps:
      env: production
      app: web
      owner: jagadeesh
      name: ansible-filters
      project: aicloudera
      component: catalogue

  tasks:
   - name: greeting example
     ansible.builtin.debug:
      msg: "Hello, Jagadeesh {{ GREETING | default('Good Morning') }}!"
      #msg: "Hello, {{ 'world' | upper }}!"
   - name: show the current date and time
     ansible.builtin.debug:
      msg: "Current date and time: {{ ansible_date_time.iso8601 }}"
        
   - name: convert string to list    
     ansible.builtin.debug:
      msg: "Topics: {{ TOPICS | split(', ') }}"    

   - name: convert map to list
     ansible.builtin.debug:
      msg: "{{ TagsMaps | dict2items }}"