- name: demo on filters
  hosts: local
  connection: local
  become: true
  tasks:
   - name: greeting example
     ansible.builtin.debug:
      msg: "Hello, Jagadeesh {{ GREETING | default('Good Morning') }}!"
      #msg: "Hello, {{ 'world' | upper }}!"