[webservers]
localhost ansible_connection=local

[webservers:vars]
ansible_python_interpreter=/usr/bin/python3

[webserver]


[local]
localhost

[local:vars]
NAME="jagadeesh from inventory"
ORG="cloudops from inventory"
EXPERTISE="ansible from inventory"
